#!/usr/bin/env php
<?php

echo "==============================\n";
echo "Git pre-commit hooks start.\n\n";
$startTime = microtime(true);

system(sprintf('php "%1$s/vendor/bin/phpstan.phar" analyse -c "%1$s/phpstan.neon" "%1$s/src" -l 6', dirname(__DIR__, 2)), $response);

if (0 !== $response) {
    echo endOutput($startTime);
    die(1);
}

echo endOutput($startTime);

function endOutput($startTime) 
{
    return "\nGit pre-commit hooks finish.
            \rВремя: ".(microtime(true) - $startTime)." сек.
            \r==============================\n";
}
